### ISSUE TITLE
1.Take  Users  Current Lan -Lon.

### ISSUE THREAD

**Issue by JamesNikolaidis** [TransCoders/Locate_Nearest_Stores#2]
Find to get somehow the Lon-Lan coordinates from Google's GPS.

**Comment by AlexandrosChatzis** [comment]
Προτεραιότητα σαν issue!!!

**Comment by AlexandrosChatzis** [comment]
εγινε επιτυχως το location
τωρα το μονο που μενει ειναι να ενωσουμε ολο τον κωδικα
