### ISSUE TITLE
Bug at my location find

### ISSUE THREAD

**Issue by TasosTilsi** [TransCoders/Locate_Nearest_Stores#6]
Παιδιά στο κινητό που το τρέχω δεν με βρίσκει την τοποθεσία μου, ας το κοιτάξει λίγο οποίος το έκανε την προηγούμενη φορά!

**Comment by JamesNikolaidis** [comment]
Bug δεν μου λειτουργεί το key της Google , πρεπεί να το λύσουμε.

**Comment by AlexandrosChatzis** [comment]
Παιδια εγω το έκανα το τεσταρα και σε κινητό ειναι όλα ok
